BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
SIMULATOR_GPU_ID: [0 , 1]
TORCH_GPU_ID: 2
NUM_PROCESSES: 1
TENSORBOARD_DIR: /data/zirshad/VLNCE-data/data/tensorboard_dirs/cma/run_2
CHECKPOINT_FOLDER: /data/zirshad/VLNCE-data/data/checkpoints/cma/run_2
EVAL_CKPT_PATH_DIR: /data/zirshad/VLNCE-data/data/checkpoints/cma 

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_seen
  EPISODE_COUNT: 50000
  VAL_LOG_DIR : validation_logging/cma/run_2

DAGGER:
  ITERATIONS: 1
  EPOCHS: 45
  UPDATE_SIZE: 10819
  BATCH_SIZE: 5
  P: 1.0
  PRELOAD_LMDB_FEATURES: True
  LMDB_FEATURES_DIR: /data/zirshad/VLNCE-data/data/trajectory_dir/cma/trajectories.lmdb

MODEL:
  INSTRUCTION_ENCODER:
    bidirectional: True

  CMA:
    use: True
