BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
SIMULATOR_GPU_ID: [1]
TORCH_GPU_ID: 1
NUM_PROCESSES: 4
TENSORBOARD_DIR: /data/zirshad/VLNCE-data/data/tensorboard_dirs/cma_da
CHECKPOINT_FOLDER: /data/zirshad/VLNCE-data/data/checkpoints/cma_da
EVAL_CKPT_PATH_DIR: /data/zirshad/VLNCE-data/data/checkpoints/cma_da

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: 50000

DAGGER:
  ITERATIONS: 10
  EPOCHS: 4
  UPDATE_SIZE: 5000
  BATCH_SIZE: 5
  P: 0.75
  LMDB_FEATURES_DIR: /data/zirshad/VLNCE-data/data/trajectory_dir/cma_da/trajectories.lmdb

MODEL:
  INSTRUCTION_ENCODER:
    bidirectional: True

  CMA:
    use: True
