BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
SIMULATOR_GPU_ID: [0 , 1]
TORCH_GPU_ID: 2
NUM_PROCESSES: 1
TENSORBOARD_DIR: /data/zirshad/VLNCE-data/data/tensorboard_dirs/seq2seq_da/run_2
CHECKPOINT_FOLDER: /data/zirshad/VLNCE-data/data/checkpoints/seq2seq_da/run_2
EVAL_CKPT_PATH_DIR: /data/zirshad/VLNCE-data/data/checkpoints/seq2seq_da

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: 50000
  VAL_LOG_DIR : validation_logging/seq2seq_da

DAGGER:
  ITERATIONS: 10
  EPOCHS: 4
  UPDATE_SIZE: 5000
  BATCH_SIZE: 5
  P: 0.75
  PRELOAD_LMDB_FEATURES: True
  LMDB_FEATURES_DIR: /data/zirshad/VLNCE-data/data/trajectory_dir/seq2seq_da/trajectories.lmdb
