BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
SIMULATOR_GPU_ID: [0]
TORCH_GPU_ID: 1
NUM_PROCESSES: 4
TENSORBOARD_DIR: /data/zirshad/VLNCE-data/data/tensorboard_dirs/seq2seq_pm
CHECKPOINT_FOLDER: /data/zirshad/VLNCE-data/data/checkpoints/seq2seq_pm
EVAL_CKPT_PATH_DIR: /data/zirshad/VLNCE-data/data/checkpoints/seq2seq_pm/ckpt.14.pth 

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: 50000
  VAL_LOG_DIR : validation_logging/seq2seq_pm

DAGGER:
  ITERATIONS: 1
  EPOCHS: 15
  UPDATE_SIZE: 10819
  BATCH_SIZE: 5
  P: 1.0
  PRELOAD_LMDB_FEATURES: True
  LMDB_FEATURES_DIR: /data/zirshad/VLNCE-data/data/trajectory_dir/seq2seq/trajectories.lmdb

MODEL:
  PROGRESS_MONITOR:
    use: True
