BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
SIMULATOR_GPU_ID: [1]
TORCH_GPU_ID: 0
NUM_PROCESSES: 2

TENSORBOARD_DIR: /data/zirshad/VLNCE-data/data/tensorboard_dirs/seq2seq_sem_text_attn/test
CHECKPOINT_FOLDER: /data/zirshad/VLNCE-data/data/checkpoints/seq2seq_sem_text_attn/test
EVAL_CKPT_PATH_DIR: /data/zirshad/VLNCE-data/data/checkpoints/seq2seq_sem_text_attn/test

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_seen
  EPISODE_COUNT: 2
  VAL_LOG_DIR : validation_logging/seq2seq_sem_text_attn
DAGGER:
  ITERATIONS: 1
  EPOCHS: 25
  UPDATE_SIZE: 10819
  BATCH_SIZE: 2
  P: 1.0
  PRELOAD_LMDB_FEATURES: True
  LMDB_FEATURES_DIR: /data/zirshad/VLNCE-data/data/trajectory_dir/seq2seq_sem_attn/test/trajectories.lmdb

MODEL:
  SEM_TEXT_ATTN:
    use: True
  PROGRESS_MONITOR:
    use: True
