BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
SIMULATOR_GPU_ID: [2]
TORCH_GPU_ID: 2
NUM_PROCESSES: 1

TENSORBOARD_DIR: /data/zirshad/VLNCE-data/data/tensorboard_dirs/seq2seq_sem_attn/run_2
CHECKPOINT_FOLDER: /data/zirshad/VLNCE-data/data/checkpoints/seq2seq_sem_attn/run_2
EVAL_CKPT_PATH_DIR: /data/zirshad/VLNCE-data/data/checkpoints/seq2seq_sem_attn/ckpt.8.pth

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: 50000
  VAL_LOG_DIR : validation_logging/seq2seq_sem_attn
DAGGER:
  ITERATIONS: 1
  EPOCHS: 10
  UPDATE_SIZE: 10819
  BATCH_SIZE: 2
  P: 1.0
  PRELOAD_LMDB_FEATURES: True
  LMDB_FEATURES_DIR: /data/zirshad/VLNCE-data/data/trajectory_dir/seq2seq_sem_attn/trajectories.lmdb

MODEL:
  SEM_ATTN_ENCODER:
    use: True
  INSTRUCTION_ENCODER:
    use_pretrained_embeddings: False
    is_bert: True
